//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZbaBotApi.ZbaBotService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZBAHearing", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ZBAHearing : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalendarNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZoningCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParcelTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProposalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttorneyField;
        
        private System.DateTime HearingDateField;
        
        private System.DateTime AppealDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullAddressField;
        
        private System.Nullable<double> LatField;
        
        private System.Nullable<double> LongField;
        
        private bool TaxDelinquentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CalendarNumber {
            get {
                return this.CalendarNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CalendarNumberField, value) != true)) {
                    this.CalendarNumberField = value;
                    this.RaisePropertyChanged("CalendarNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ApplicationNumber {
            get {
                return this.ApplicationNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNumberField, value) != true)) {
                    this.ApplicationNumberField = value;
                    this.RaisePropertyChanged("ApplicationNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ZoningCategory {
            get {
                return this.ZoningCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ZoningCategoryField, value) != true)) {
                    this.ZoningCategoryField = value;
                    this.RaisePropertyChanged("ZoningCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ParcelType {
            get {
                return this.ParcelTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ParcelTypeField, value) != true)) {
                    this.ParcelTypeField = value;
                    this.RaisePropertyChanged("ParcelType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Proposal {
            get {
                return this.ProposalField;
            }
            set {
                if ((object.ReferenceEquals(this.ProposalField, value) != true)) {
                    this.ProposalField = value;
                    this.RaisePropertyChanged("Proposal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Applicant {
            get {
                return this.ApplicantField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicantField, value) != true)) {
                    this.ApplicantField = value;
                    this.RaisePropertyChanged("Applicant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Attorney {
            get {
                return this.AttorneyField;
            }
            set {
                if ((object.ReferenceEquals(this.AttorneyField, value) != true)) {
                    this.AttorneyField = value;
                    this.RaisePropertyChanged("Attorney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime HearingDate {
            get {
                return this.HearingDateField;
            }
            set {
                if ((this.HearingDateField.Equals(value) != true)) {
                    this.HearingDateField = value;
                    this.RaisePropertyChanged("HearingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime AppealDate {
            get {
                return this.AppealDateField;
            }
            set {
                if ((this.AppealDateField.Equals(value) != true)) {
                    this.AppealDateField = value;
                    this.RaisePropertyChanged("AppealDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string FullAddress {
            get {
                return this.FullAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.FullAddressField, value) != true)) {
                    this.FullAddressField = value;
                    this.RaisePropertyChanged("FullAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.Nullable<double> Lat {
            get {
                return this.LatField;
            }
            set {
                if ((this.LatField.Equals(value) != true)) {
                    this.LatField = value;
                    this.RaisePropertyChanged("Lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Nullable<double> Long {
            get {
                return this.LongField;
            }
            set {
                if ((this.LongField.Equals(value) != true)) {
                    this.LongField = value;
                    this.RaisePropertyChanged("Long");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public bool TaxDelinquent {
            get {
                return this.TaxDelinquentField;
            }
            set {
                if ((this.TaxDelinquentField.Equals(value) != true)) {
                    this.TaxDelinquentField = value;
                    this.RaisePropertyChanged("TaxDelinquent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OPAAccount", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OPAAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZbaBotApi.ZbaBotService.Property[] SuggestedPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZbaBotApi.ZbaBotService.SuggestedAddress[] SuggestedAddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZbaBotApi.ZbaBotService.TaxRecord TaxRecordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZbaBotApi.ZbaBotService.Valuation ValuationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZbaBotApi.ZbaBotService.Owner OwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZbaBotApi.ZbaBotService.Details DetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UnitNumber {
            get {
                return this.UnitNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitNumberField, value) != true)) {
                    this.UnitNumberField = value;
                    this.RaisePropertyChanged("UnitNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ZbaBotApi.ZbaBotService.Property[] SuggestedProperties {
            get {
                return this.SuggestedPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.SuggestedPropertiesField, value) != true)) {
                    this.SuggestedPropertiesField = value;
                    this.RaisePropertyChanged("SuggestedProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ZbaBotApi.ZbaBotService.SuggestedAddress[] SuggestedAddresses {
            get {
                return this.SuggestedAddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.SuggestedAddressesField, value) != true)) {
                    this.SuggestedAddressesField = value;
                    this.RaisePropertyChanged("SuggestedAddresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public ZbaBotApi.ZbaBotService.TaxRecord TaxRecord {
            get {
                return this.TaxRecordField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxRecordField, value) != true)) {
                    this.TaxRecordField = value;
                    this.RaisePropertyChanged("TaxRecord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public ZbaBotApi.ZbaBotService.Valuation Valuation {
            get {
                return this.ValuationField;
            }
            set {
                if ((object.ReferenceEquals(this.ValuationField, value) != true)) {
                    this.ValuationField = value;
                    this.RaisePropertyChanged("Valuation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public ZbaBotApi.ZbaBotService.Owner Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public ZbaBotApi.ZbaBotService.Details Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxRecord", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TaxRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZbaBotApi.ZbaBotService.TaxInfoYear[] TaxInfoYearsField;
        
        private bool RevenueDownField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ZbaBotApi.ZbaBotService.TaxInfoYear[] TaxInfoYears {
            get {
                return this.TaxInfoYearsField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxInfoYearsField, value) != true)) {
                    this.TaxInfoYearsField = value;
                    this.RaisePropertyChanged("TaxInfoYears");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool RevenueDown {
            get {
                return this.RevenueDownField;
            }
            set {
                if ((this.RevenueDownField.Equals(value) != true)) {
                    this.RevenueDownField = value;
                    this.RaisePropertyChanged("RevenueDown");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Valuation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Valuation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZbaBotApi.ZbaBotService.ValuationYear[] ValuationYearsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ZbaBotApi.ZbaBotService.ValuationYear[] ValuationYears {
            get {
                return this.ValuationYearsField;
            }
            set {
                if ((object.ReferenceEquals(this.ValuationYearsField, value) != true)) {
                    this.ValuationYearsField = value;
                    this.RaisePropertyChanged("ValuationYears");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Owner", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Owner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailingAddress1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailingAddress2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailingCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailingStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailingZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MailingAddress1 {
            get {
                return this.MailingAddress1Field;
            }
            set {
                if ((object.ReferenceEquals(this.MailingAddress1Field, value) != true)) {
                    this.MailingAddress1Field = value;
                    this.RaisePropertyChanged("MailingAddress1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MailingAddress2 {
            get {
                return this.MailingAddress2Field;
            }
            set {
                if ((object.ReferenceEquals(this.MailingAddress2Field, value) != true)) {
                    this.MailingAddress2Field = value;
                    this.RaisePropertyChanged("MailingAddress2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MailingCity {
            get {
                return this.MailingCityField;
            }
            set {
                if ((object.ReferenceEquals(this.MailingCityField, value) != true)) {
                    this.MailingCityField = value;
                    this.RaisePropertyChanged("MailingCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string MailingState {
            get {
                return this.MailingStateField;
            }
            set {
                if ((object.ReferenceEquals(this.MailingStateField, value) != true)) {
                    this.MailingStateField = value;
                    this.RaisePropertyChanged("MailingState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string MailingZip {
            get {
                return this.MailingZipField;
            }
            set {
                if ((object.ReferenceEquals(this.MailingZipField, value) != true)) {
                    this.MailingZipField = value;
                    this.RaisePropertyChanged("MailingZip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Details", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Details : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LandAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImprovementAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZoningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZoningDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CouncilDistrictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BeginPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarketValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RealEstateTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalAssessmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssessedLandTaxableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssessedImprovementTaxableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssessedLandExemptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssessedImprovementExemptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaleDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalePriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LandArea {
            get {
                return this.LandAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.LandAreaField, value) != true)) {
                    this.LandAreaField = value;
                    this.RaisePropertyChanged("LandArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ImprovementArea {
            get {
                return this.ImprovementAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.ImprovementAreaField, value) != true)) {
                    this.ImprovementAreaField = value;
                    this.RaisePropertyChanged("ImprovementArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Zoning {
            get {
                return this.ZoningField;
            }
            set {
                if ((object.ReferenceEquals(this.ZoningField, value) != true)) {
                    this.ZoningField = value;
                    this.RaisePropertyChanged("Zoning");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ZoningDescription {
            get {
                return this.ZoningDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ZoningDescriptionField, value) != true)) {
                    this.ZoningDescriptionField = value;
                    this.RaisePropertyChanged("ZoningDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Condition {
            get {
                return this.ConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConditionField, value) != true)) {
                    this.ConditionField = value;
                    this.RaisePropertyChanged("Condition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CouncilDistrict {
            get {
                return this.CouncilDistrictField;
            }
            set {
                if ((object.ReferenceEquals(this.CouncilDistrictField, value) != true)) {
                    this.CouncilDistrictField = value;
                    this.RaisePropertyChanged("CouncilDistrict");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string BeginPoint {
            get {
                return this.BeginPointField;
            }
            set {
                if ((object.ReferenceEquals(this.BeginPointField, value) != true)) {
                    this.BeginPointField = value;
                    this.RaisePropertyChanged("BeginPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string MarketValue {
            get {
                return this.MarketValueField;
            }
            set {
                if ((object.ReferenceEquals(this.MarketValueField, value) != true)) {
                    this.MarketValueField = value;
                    this.RaisePropertyChanged("MarketValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string RealEstateTax {
            get {
                return this.RealEstateTaxField;
            }
            set {
                if ((object.ReferenceEquals(this.RealEstateTaxField, value) != true)) {
                    this.RealEstateTaxField = value;
                    this.RaisePropertyChanged("RealEstateTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string TotalAssessment {
            get {
                return this.TotalAssessmentField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalAssessmentField, value) != true)) {
                    this.TotalAssessmentField = value;
                    this.RaisePropertyChanged("TotalAssessment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string AssessedLandTaxable {
            get {
                return this.AssessedLandTaxableField;
            }
            set {
                if ((object.ReferenceEquals(this.AssessedLandTaxableField, value) != true)) {
                    this.AssessedLandTaxableField = value;
                    this.RaisePropertyChanged("AssessedLandTaxable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string AssessedImprovementTaxable {
            get {
                return this.AssessedImprovementTaxableField;
            }
            set {
                if ((object.ReferenceEquals(this.AssessedImprovementTaxableField, value) != true)) {
                    this.AssessedImprovementTaxableField = value;
                    this.RaisePropertyChanged("AssessedImprovementTaxable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string AssessedLandExempt {
            get {
                return this.AssessedLandExemptField;
            }
            set {
                if ((object.ReferenceEquals(this.AssessedLandExemptField, value) != true)) {
                    this.AssessedLandExemptField = value;
                    this.RaisePropertyChanged("AssessedLandExempt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string AssessedImprovementExempt {
            get {
                return this.AssessedImprovementExemptField;
            }
            set {
                if ((object.ReferenceEquals(this.AssessedImprovementExemptField, value) != true)) {
                    this.AssessedImprovementExemptField = value;
                    this.RaisePropertyChanged("AssessedImprovementExempt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string SaleDate {
            get {
                return this.SaleDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SaleDateField, value) != true)) {
                    this.SaleDateField = value;
                    this.RaisePropertyChanged("SaleDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string SalePrice {
            get {
                return this.SalePriceField;
            }
            set {
                if ((object.ReferenceEquals(this.SalePriceField, value) != true)) {
                    this.SalePriceField = value;
                    this.RaisePropertyChanged("SalePrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Property", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Property : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalePriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaleDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OwnerName {
            get {
                return this.OwnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerNameField, value) != true)) {
                    this.OwnerNameField = value;
                    this.RaisePropertyChanged("OwnerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SalePrice {
            get {
                return this.SalePriceField;
            }
            set {
                if ((object.ReferenceEquals(this.SalePriceField, value) != true)) {
                    this.SalePriceField = value;
                    this.RaisePropertyChanged("SalePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SaleDate {
            get {
                return this.SaleDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SaleDateField, value) != true)) {
                    this.SaleDateField = value;
                    this.RaisePropertyChanged("SaleDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SuggestedAddress", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SuggestedAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddressName {
            get {
                return this.AddressNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressNameField, value) != true)) {
                    this.AddressNameField = value;
                    this.RaisePropertyChanged("AddressName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxInfoYear", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TaxInfoYear : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YearField;
        
        private double PrincipalField;
        
        private double InterestField;
        
        private double PenaltyField;
        
        private double OtherField;
        
        private double TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SolicitorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Year {
            get {
                return this.YearField;
            }
            set {
                if ((object.ReferenceEquals(this.YearField, value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double Principal {
            get {
                return this.PrincipalField;
            }
            set {
                if ((this.PrincipalField.Equals(value) != true)) {
                    this.PrincipalField = value;
                    this.RaisePropertyChanged("Principal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Interest {
            get {
                return this.InterestField;
            }
            set {
                if ((this.InterestField.Equals(value) != true)) {
                    this.InterestField = value;
                    this.RaisePropertyChanged("Interest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Penalty {
            get {
                return this.PenaltyField;
            }
            set {
                if ((this.PenaltyField.Equals(value) != true)) {
                    this.PenaltyField = value;
                    this.RaisePropertyChanged("Penalty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Other {
            get {
                return this.OtherField;
            }
            set {
                if ((this.OtherField.Equals(value) != true)) {
                    this.OtherField = value;
                    this.RaisePropertyChanged("Other");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Lien {
            get {
                return this.LienField;
            }
            set {
                if ((object.ReferenceEquals(this.LienField, value) != true)) {
                    this.LienField = value;
                    this.RaisePropertyChanged("Lien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Solicitor {
            get {
                return this.SolicitorField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitorField, value) != true)) {
                    this.SolicitorField = value;
                    this.RaisePropertyChanged("Solicitor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValuationYear", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ValuationYear : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarketValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssessedLandTaxableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssessedImprovementTaxableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssessedLandExemptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssessedImprovementExemptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalAssessmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GrossTaxField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Year {
            get {
                return this.YearField;
            }
            set {
                if ((object.ReferenceEquals(this.YearField, value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MarketValue {
            get {
                return this.MarketValueField;
            }
            set {
                if ((object.ReferenceEquals(this.MarketValueField, value) != true)) {
                    this.MarketValueField = value;
                    this.RaisePropertyChanged("MarketValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AssessedLandTaxable {
            get {
                return this.AssessedLandTaxableField;
            }
            set {
                if ((object.ReferenceEquals(this.AssessedLandTaxableField, value) != true)) {
                    this.AssessedLandTaxableField = value;
                    this.RaisePropertyChanged("AssessedLandTaxable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AssessedImprovementTaxable {
            get {
                return this.AssessedImprovementTaxableField;
            }
            set {
                if ((object.ReferenceEquals(this.AssessedImprovementTaxableField, value) != true)) {
                    this.AssessedImprovementTaxableField = value;
                    this.RaisePropertyChanged("AssessedImprovementTaxable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AssessedLandExempt {
            get {
                return this.AssessedLandExemptField;
            }
            set {
                if ((object.ReferenceEquals(this.AssessedLandExemptField, value) != true)) {
                    this.AssessedLandExemptField = value;
                    this.RaisePropertyChanged("AssessedLandExempt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AssessedImprovementExempt {
            get {
                return this.AssessedImprovementExemptField;
            }
            set {
                if ((object.ReferenceEquals(this.AssessedImprovementExemptField, value) != true)) {
                    this.AssessedImprovementExemptField = value;
                    this.RaisePropertyChanged("AssessedImprovementExempt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TotalAssessment {
            get {
                return this.TotalAssessmentField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalAssessmentField, value) != true)) {
                    this.TotalAssessmentField = value;
                    this.RaisePropertyChanged("TotalAssessment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string GrossTax {
            get {
                return this.GrossTaxField;
            }
            set {
                if ((object.ReferenceEquals(this.GrossTaxField, value) != true)) {
                    this.GrossTaxField = value;
                    this.RaisePropertyChanged("GrossTax");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZbaBotService.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostHearings", ReplyAction="*")]
        ZbaBotApi.ZbaBotService.PostHearingsResponse PostHearings(ZbaBotApi.ZbaBotService.PostHearingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostHearings", ReplyAction="*")]
        System.Threading.Tasks.Task<ZbaBotApi.ZbaBotService.PostHearingsResponse> PostHearingsAsync(ZbaBotApi.ZbaBotService.PostHearingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOPAAccountByStreetAddress", ReplyAction="*")]
        ZbaBotApi.ZbaBotService.GetOPAAccountByStreetAddressResponse GetOPAAccountByStreetAddress(ZbaBotApi.ZbaBotService.GetOPAAccountByStreetAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOPAAccountByStreetAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<ZbaBotApi.ZbaBotService.GetOPAAccountByStreetAddressResponse> GetOPAAccountByStreetAddressAsync(ZbaBotApi.ZbaBotService.GetOPAAccountByStreetAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOPAAccountByAccountNumber", ReplyAction="*")]
        ZbaBotApi.ZbaBotService.GetOPAAccountByAccountNumberResponse GetOPAAccountByAccountNumber(ZbaBotApi.ZbaBotService.GetOPAAccountByAccountNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOPAAccountByAccountNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<ZbaBotApi.ZbaBotService.GetOPAAccountByAccountNumberResponse> GetOPAAccountByAccountNumberAsync(ZbaBotApi.ZbaBotService.GetOPAAccountByAccountNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOPAAccountByAccountOwner", ReplyAction="*")]
        ZbaBotApi.ZbaBotService.GetOPAAccountByAccountOwnerResponse GetOPAAccountByAccountOwner(ZbaBotApi.ZbaBotService.GetOPAAccountByAccountOwnerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOPAAccountByAccountOwner", ReplyAction="*")]
        System.Threading.Tasks.Task<ZbaBotApi.ZbaBotService.GetOPAAccountByAccountOwnerResponse> GetOPAAccountByAccountOwnerAsync(ZbaBotApi.ZbaBotService.GetOPAAccountByAccountOwnerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostHearingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostHearings", Namespace="http://tempuri.org/", Order=0)]
        public ZbaBotApi.ZbaBotService.PostHearingsRequestBody Body;
        
        public PostHearingsRequest() {
        }
        
        public PostHearingsRequest(ZbaBotApi.ZbaBotService.PostHearingsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostHearingsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ZbaBotApi.ZbaBotService.ZBAHearing[] hearings;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string postKey;
        
        public PostHearingsRequestBody() {
        }
        
        public PostHearingsRequestBody(ZbaBotApi.ZbaBotService.ZBAHearing[] hearings, string postKey) {
            this.hearings = hearings;
            this.postKey = postKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostHearingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostHearingsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZbaBotApi.ZbaBotService.PostHearingsResponseBody Body;
        
        public PostHearingsResponse() {
        }
        
        public PostHearingsResponse(ZbaBotApi.ZbaBotService.PostHearingsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostHearingsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PostHearingsResult;
        
        public PostHearingsResponseBody() {
        }
        
        public PostHearingsResponseBody(bool PostHearingsResult) {
            this.PostHearingsResult = PostHearingsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOPAAccountByStreetAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOPAAccountByStreetAddress", Namespace="http://tempuri.org/", Order=0)]
        public ZbaBotApi.ZbaBotService.GetOPAAccountByStreetAddressRequestBody Body;
        
        public GetOPAAccountByStreetAddressRequest() {
        }
        
        public GetOPAAccountByStreetAddressRequest(ZbaBotApi.ZbaBotService.GetOPAAccountByStreetAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOPAAccountByStreetAddressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Address;
        
        public GetOPAAccountByStreetAddressRequestBody() {
        }
        
        public GetOPAAccountByStreetAddressRequestBody(string Address) {
            this.Address = Address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOPAAccountByStreetAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOPAAccountByStreetAddressResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZbaBotApi.ZbaBotService.GetOPAAccountByStreetAddressResponseBody Body;
        
        public GetOPAAccountByStreetAddressResponse() {
        }
        
        public GetOPAAccountByStreetAddressResponse(ZbaBotApi.ZbaBotService.GetOPAAccountByStreetAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOPAAccountByStreetAddressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ZbaBotApi.ZbaBotService.OPAAccount GetOPAAccountByStreetAddressResult;
        
        public GetOPAAccountByStreetAddressResponseBody() {
        }
        
        public GetOPAAccountByStreetAddressResponseBody(ZbaBotApi.ZbaBotService.OPAAccount GetOPAAccountByStreetAddressResult) {
            this.GetOPAAccountByStreetAddressResult = GetOPAAccountByStreetAddressResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOPAAccountByAccountNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOPAAccountByAccountNumber", Namespace="http://tempuri.org/", Order=0)]
        public ZbaBotApi.ZbaBotService.GetOPAAccountByAccountNumberRequestBody Body;
        
        public GetOPAAccountByAccountNumberRequest() {
        }
        
        public GetOPAAccountByAccountNumberRequest(ZbaBotApi.ZbaBotService.GetOPAAccountByAccountNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOPAAccountByAccountNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accountNumber;
        
        public GetOPAAccountByAccountNumberRequestBody() {
        }
        
        public GetOPAAccountByAccountNumberRequestBody(string accountNumber) {
            this.accountNumber = accountNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOPAAccountByAccountNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOPAAccountByAccountNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZbaBotApi.ZbaBotService.GetOPAAccountByAccountNumberResponseBody Body;
        
        public GetOPAAccountByAccountNumberResponse() {
        }
        
        public GetOPAAccountByAccountNumberResponse(ZbaBotApi.ZbaBotService.GetOPAAccountByAccountNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOPAAccountByAccountNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ZbaBotApi.ZbaBotService.OPAAccount GetOPAAccountByAccountNumberResult;
        
        public GetOPAAccountByAccountNumberResponseBody() {
        }
        
        public GetOPAAccountByAccountNumberResponseBody(ZbaBotApi.ZbaBotService.OPAAccount GetOPAAccountByAccountNumberResult) {
            this.GetOPAAccountByAccountNumberResult = GetOPAAccountByAccountNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOPAAccountByAccountOwnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOPAAccountByAccountOwner", Namespace="http://tempuri.org/", Order=0)]
        public ZbaBotApi.ZbaBotService.GetOPAAccountByAccountOwnerRequestBody Body;
        
        public GetOPAAccountByAccountOwnerRequest() {
        }
        
        public GetOPAAccountByAccountOwnerRequest(ZbaBotApi.ZbaBotService.GetOPAAccountByAccountOwnerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOPAAccountByAccountOwnerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string owner;
        
        public GetOPAAccountByAccountOwnerRequestBody() {
        }
        
        public GetOPAAccountByAccountOwnerRequestBody(string owner) {
            this.owner = owner;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOPAAccountByAccountOwnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOPAAccountByAccountOwnerResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZbaBotApi.ZbaBotService.GetOPAAccountByAccountOwnerResponseBody Body;
        
        public GetOPAAccountByAccountOwnerResponse() {
        }
        
        public GetOPAAccountByAccountOwnerResponse(ZbaBotApi.ZbaBotService.GetOPAAccountByAccountOwnerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOPAAccountByAccountOwnerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ZbaBotApi.ZbaBotService.OPAAccount GetOPAAccountByAccountOwnerResult;
        
        public GetOPAAccountByAccountOwnerResponseBody() {
        }
        
        public GetOPAAccountByAccountOwnerResponseBody(ZbaBotApi.ZbaBotService.OPAAccount GetOPAAccountByAccountOwnerResult) {
            this.GetOPAAccountByAccountOwnerResult = GetOPAAccountByAccountOwnerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : ZbaBotApi.ZbaBotService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<ZbaBotApi.ZbaBotService.ServiceSoap>, ZbaBotApi.ZbaBotService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ZbaBotApi.ZbaBotService.PostHearingsResponse PostHearings(ZbaBotApi.ZbaBotService.PostHearingsRequest request) {
            return base.Channel.PostHearings(request);
        }
        
        public System.Threading.Tasks.Task<ZbaBotApi.ZbaBotService.PostHearingsResponse> PostHearingsAsync(ZbaBotApi.ZbaBotService.PostHearingsRequest request) {
            return base.Channel.PostHearingsAsync(request);
        }
        
        public ZbaBotApi.ZbaBotService.GetOPAAccountByStreetAddressResponse GetOPAAccountByStreetAddress(ZbaBotApi.ZbaBotService.GetOPAAccountByStreetAddressRequest request) {
            return base.Channel.GetOPAAccountByStreetAddress(request);
        }
        
        public System.Threading.Tasks.Task<ZbaBotApi.ZbaBotService.GetOPAAccountByStreetAddressResponse> GetOPAAccountByStreetAddressAsync(ZbaBotApi.ZbaBotService.GetOPAAccountByStreetAddressRequest request) {
            return base.Channel.GetOPAAccountByStreetAddressAsync(request);
        }
        
        public ZbaBotApi.ZbaBotService.GetOPAAccountByAccountNumberResponse GetOPAAccountByAccountNumber(ZbaBotApi.ZbaBotService.GetOPAAccountByAccountNumberRequest request) {
            return base.Channel.GetOPAAccountByAccountNumber(request);
        }
        
        public System.Threading.Tasks.Task<ZbaBotApi.ZbaBotService.GetOPAAccountByAccountNumberResponse> GetOPAAccountByAccountNumberAsync(ZbaBotApi.ZbaBotService.GetOPAAccountByAccountNumberRequest request) {
            return base.Channel.GetOPAAccountByAccountNumberAsync(request);
        }
        
        public ZbaBotApi.ZbaBotService.GetOPAAccountByAccountOwnerResponse GetOPAAccountByAccountOwner(ZbaBotApi.ZbaBotService.GetOPAAccountByAccountOwnerRequest request) {
            return base.Channel.GetOPAAccountByAccountOwner(request);
        }
        
        public System.Threading.Tasks.Task<ZbaBotApi.ZbaBotService.GetOPAAccountByAccountOwnerResponse> GetOPAAccountByAccountOwnerAsync(ZbaBotApi.ZbaBotService.GetOPAAccountByAccountOwnerRequest request) {
            return base.Channel.GetOPAAccountByAccountOwnerAsync(request);
        }
    }
}
